#!/usr/bin/env python3
"""fixed-facts-schema: a saved emulator records the science it was born under.

An emulator answers questions about one cosmology, over one region of one
parameter space. A saved emulator used to record neither. It kept the names of
the parameters that were sampled and nothing about the world those names lived
in: not what was held fixed while they varied, not the interval each ranged
over, not which dataset the weights were fitted to. So a matter-power emulator
trained with a varying dark-energy equation of state could be handed to a
likelihood that assumes a cosmological constant, and it would answer.

This check drives the record that closes that hole (emulator/fixed_facts.py).
It proves, on real HDF5 files:

  the round trip     both blocks survive a write and a read unchanged
  the two-way check  the blocks in the file must still match the producer's own
                     text stored beside them, so a record rewritten anywhere
                     between the generator and the file is caught
  the refusals       a file with no record, a record in a grammar this code does
                     not know, a coordinate that is both sampled and held fixed,
                     and a whitening geometry that disagrees with the record
                     about the parameter order, are each refused rather than
                     guessed at, and each refusal says what to do about it
  the identity       the dataset's identity really is the digest of the chain
                     that was published, recomputed here from the bytes

It then proves the three comparison laws the record exists to make possible.
They ask three different questions, and conflating them is how the consumers of
these artifacts ended up comparing parameter-axis names and calling it a
cosmology check:

  vertical    does this artifact belong to the cosmology being sampled? every
              coordinate the artifact held fixed must equal the value the
              resolved global model gives for it
  horizontal  do these two artifacts belong to each other? one dataset, one
              cosmology, one list of sampled coordinates, compared by equality
  domain      may this artifact be asked about this point? the point must lie
              inside the region the artifact was trained over, and the region a
              PAIR may be asked about is the overlap of the two, never the union

and it carries a mutation arm for every law, which are the point of the whole
file: a check that cannot go red proves nothing. Each arm breaks one law on
purpose, confirms the leg that guards it goes red, and puts the law back.

The live proof that a REAL emulator, with real weights, survives the same round
trip needs torch and a trained network, and is owned by the save/rebuild gate.
This check owns the record's own laws, and needs no accelerator to prove them.

PS: a "sidecar" is a small companion file written next to a data file, sharing
its name stem, the way a chain's .paramnames sits beside its .1.txt. "Sampled"
parameters are the ones the generator drew values for; "fixed" ones are held at
a constant value while it draws. A parameter's "support" is the interval it was
drawn from, and the "served support" of a pair of emulators is the region both
halves were trained over. The "resolved model" is the cosmology a chain is
actually being sampled under, with every default the input YAML left unstated
already filled in. A "test double" is an emulator a gate builds in memory out of
noise to prove the machinery works: it was generated by nobody, it describes no
cosmology, it declares no support, and it must never reach a likelihood. A
"mutation arm" breaks the code deliberately to prove a check would notice.

Spec: ai/notes/artifacts-inference-warmstart.md, "fixed-facts-schema: a saved
emulator records the science it was born under."
"""
import os
import shutil
import sys
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(os.path.dirname(os.path.dirname(_HERE)))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from emulator import fixed_facts

FAILURES = []

# every leg this check is declared to produce, in the order it produces them.
# The board reconciles this list against what actually ran: a leg that never
# reached a verdict is recorded as never having run, not as having passed.
LEG_AIDS = ("fixed-facts-schema.record-round-trip",
            "fixed-facts-schema.rewritten-record-refused",
            "fixed-facts-schema.missing-record-refused",
            "fixed-facts-schema.legacy-version-refused",
            "fixed-facts-schema.sampled-and-fixed-refused",
            "fixed-facts-schema.parameter-order-enforced",
            "fixed-facts-schema.dataset-identity-is-the-chain",
            "fixed-facts-schema.vertical-law-enforced",
            "fixed-facts-schema.horizontal-law-enforced",
            "fixed-facts-schema.domain-law-enforced",
            "fixed-facts-schema.served-support-is-the-intersection",
            "fixed-facts-schema.comparison-laws-are-load-bearing",
            "fixed-facts-schema.resolved-model-read-once")

NAMES = ["omegam", "H0", "ns", "logA", "w"]

# the same coordinates without the equation of state. A half that never sampled
# w publishes this list, and a record that HOLDS w fixed cannot sample it, so
# both of those fixtures below are drawn over these four.
NAMES_WITHOUT_W = ["omegam", "H0", "ns", "logA"]

REQUESTED = {"omegam": (0.1, 0.5),
             "H0":     (55.0, 91.0),
             "ns":     (0.87, 1.07),
             "logA":   (1.61, 3.91),
             "w":      (-1.3, -0.7)}

RESOLVED = {"omegam": (0.104, 0.496),
            "H0":     (55.36, 90.64),
            "ns":     (0.872, 1.068),
            "logA":   (1.633, 3.887),
            "w":      (-1.294, -0.706)}

# The resolved global model a likelihood would be sampling under: every
# coordinate the fixture's record holds fixed, at the value the record pins,
# followed by the coordinates the emulator itself takes as inputs. The vertical
# law must read the first group and never the second. A sampled coordinate is
# validated through the region it was drawn from, not by pinning it, and w is
# here at -1.0 precisely to prove the law does not consult it.
SAMPLED_MODEL = {"mnu":    0.06,
                 "wa":     0.0,
                 "omk":    0.0,
                 "TCMB":   2.7255,
                 "nnu":    3.044,
                 "omegam": 0.3,
                 "H0":     70.0,
                 "ns":     0.96,
                 "logA":   3.0,
                 "w":      -1.0}

# A point comfortably inside every one of the fixture's resolved intervals.
# omegab is not a coordinate the fixture sampled: a consumer hands in the whole
# parameter block it happens to hold, and the domain law reads the coordinates
# it knows and ignores the rest.
INTERIOR = {"omegam": 0.3,
            "H0":     70.0,
            "ns":     0.96,
            "logA":   3.0,
            "w":      -1.0,
            "omegab": 0.048}


def report(label, ok, detail=""):
    """Record one leg's verdict and print it.

    Arguments:
      label  = what was checked, in plain English.
      ok     = True when the check held.
      detail = the evidence, printed beside the verdict.

    Returns:
      None.
    """
    print("  [" + ("PASS" if ok else "FAIL") + "] " + label + "  (" + detail
          + ")")
    if not ok:
        FAILURES.append(label)


def emit_leg(aid, n_before):
    """Print the board's terminal line for one declared leg.

    Arguments:
      aid      = the board-declared assertion id of the leg.
      n_before = how many failures had been recorded before the leg ran.

    Returns:
      True when the leg passed.
    """
    mark = "PASS" if len(FAILURES) == n_before else "FAIL"
    print("##AID " + aid + " " + mark)
    return mark == "PASS"


def emit_unavailable(aid, blocker):
    """Print the reserved terminal for a declared leg that never ran.

    A leg skipped because an earlier leg failed did not fail: it did not run at
    all, and a verdict it never produced must not read as one it did.

    Arguments:
      aid     = the board-declared assertion id of the leg that never ran.
      blocker = the aid of the upstream leg whose failure stopped it, or None
                when the check exited before any leg reached its terminal.

    Returns:
      None.
    """
    if blocker is None:
        reason = "the child exited before this leg ran"
    else:
        reason = "upstream leg " + blocker + " did not pass"
    print("##AID " + aid + " UNAVAILABLE " + reason)


def facts_sidecar(dataset_id, names, requested, resolved):
    """Build a record under the fixture's one cosmology, over the given names.

    The equation-of-state parameter w is SAMPLED by this fixture, so it must not
    also be pinned among the fixed facts; wa is fixed at zero and unsampled, so
    it may be. That asymmetry is the point of the fixture.

    Every record built through here carries the SAME fixed facts, written in one
    place. That matters for the horizontal law below, whose fixtures must differ
    in exactly one thing at a time: if two of them drifted apart on some fact
    nobody was looking at, the law would refuse for a reason the leg never meant
    to test, and the leg would still be green.

    Arguments:
      dataset_id = the identity to record, so a caller can build two records
                   that agree or disagree about which dataset they came from.
      names      = the sampled parameters, in the generator's canonical order.
      requested  = mapping name -> (low, high), the support the prior asked for.
      resolved   = mapping name -> (low, high), the support drawn from.

    Returns:
      the sidecar's text.
    """
    return fixed_facts.build_sidecar(
        dataset_id=dataset_id,
        generator="dataset_generator_mps",
        family="grid2d",
        cosmology_fixed={"mnu":  0.06,
                         "wa":   0.0,
                         "omk":  0.0,
                         "TCMB": 2.7255,
                         "nnu":  3.044},
        neutrino_convention="degenerate",
        flat_only=True,
        dark_energy_law="constant-w",
        dark_energy_inputs=["w"],
        cl_units=fixed_facts.NOT_APPLICABLE,
        base_identity="syren analytic base, mnu pinned at 0.06",
        names=names,
        requested=requested,
        resolved=resolved)


def sample_sidecar(dataset_id="sha256:" + "a" * 64):
    """Build the record a real matter-power dataset would publish.

    Arguments:
      dataset_id = the identity to record, so a caller can build two records
                   that agree or disagree about which dataset they came from.

    Returns:
      the sidecar's text.
    """
    return facts_sidecar(dataset_id=dataset_id,
                         names=NAMES,
                         requested=REQUESTED,
                         resolved=RESOLVED)


def half_without_w_sidecar(dataset_id):
    """Build the record a half that never sampled the equation of state writes.

    Every fixed fact is identical to the record above, on purpose. The two
    differ in one thing only, the list of sampled coordinates, so the only law
    that can refuse the pair is the one that compares those lists.

    Arguments:
      dataset_id = the identity to record.

    Returns:
      the sidecar's text.
    """
    support = {}
    for name in NAMES_WITHOUT_W:
        support[name] = RESOLVED[name]
    return facts_sidecar(dataset_id=dataset_id,
                         names=NAMES_WITHOUT_W,
                         requested=support,
                         resolved=support)


def box_sidecar(dataset_id, omegam_support):
    """Build a record whose omegam was drawn from the caller's interval.

    The served-support law reads the RESOLVED support only, so the requested one
    is written to match it here. The endpoint stretch that separates the two in
    a real dataset plays no part in this law.

    Arguments:
      dataset_id     = the identity to record.
      omegam_support = (low, high), the interval omegam was drawn from.

    Returns:
      the sidecar's text.
    """
    support = {}
    for name in NAMES:
        support[name] = RESOLVED[name]
    support["omegam"] = omegam_support
    return facts_sidecar(dataset_id=dataset_id,
                         names=NAMES,
                         requested=support,
                         resolved=support)


def pinned_w_sidecar(dataset_id, w_value):
    """Build a record that HELD the equation of state fixed rather than sampling.

    The fixture above samples w, and the schema refuses a coordinate that is
    both sampled and pinned. So to prove the horizontal law catches two records
    that pin one coordinate at two different values, w has to be a pinned
    coordinate, which means this record cannot sample it.

    Arguments:
      dataset_id = the identity to record.
      w_value    = the equation of state this record was generated under.

    Returns:
      the sidecar's text.
    """
    support = {}
    for name in NAMES_WITHOUT_W:
        support[name] = RESOLVED[name]
    return fixed_facts.build_sidecar(
        dataset_id=dataset_id,
        generator="dataset_generator_mps",
        family="grid2d",
        cosmology_fixed={"mnu":  0.06,
                         "w":    w_value,
                         "wa":   0.0,
                         "omk":  0.0,
                         "TCMB": 2.7255,
                         "nnu":  3.044},
        neutrino_convention="degenerate",
        flat_only=True,
        dark_energy_law="constant-w",
        dark_energy_inputs=["w"],
        cl_units=fixed_facts.NOT_APPLICABLE,
        base_identity="syren analytic base, mnu pinned at 0.06",
        names=NAMES_WITHOUT_W,
        requested=support,
        resolved=support)


def double_sidecar(label):
    """Build the record a gate's test double publishes.

    Arguments:
      label = what the double is for. Two doubles built under one label carry
              one identity; two built under different labels do not.

    Returns:
      the sidecar's text.
    """
    return fixed_facts.synthetic_sidecar(names=NAMES, label=label)


def blocks_of(text):
    """Parse one sidecar's text into the two blocks the laws are asked about.

    Arguments:
      text = the sidecar's text, from build_sidecar or synthetic_sidecar.

    Returns:
      the two blocks, validated, as fixed_facts.parse_sidecar returns them.
    """
    return fixed_facts.parse_sidecar(text=text, where="fixture")


def write_artifact(path, text, schema_version=fixed_facts.SCHEMA_VERSION):
    """Write one HDF5 file carrying nothing but the record, and its version.

    Arguments:
      path           = where to write the file.
      text           = the producer sidecar's text to copy into it.
      schema_version = the version to announce, so a caller can forge an old
                       one.

    Returns:
      None.
    """
    import h5py
    with h5py.File(path, "w") as f:
        f.attrs["schema_version"] = schema_version
        fixed_facts.write_h5(f=f, sidecar_text=text)


def read_artifact(path):
    """Read the record back out of one HDF5 file, enforcing every law.

    Arguments:
      path = the file to read.

    Returns:
      the two blocks, as fixed_facts.read_h5 returns them.
    """
    import h5py
    with h5py.File(path, "r") as f:
        version = int(f.attrs["schema_version"])
        return fixed_facts.read_h5(f=f, schema_version=version, where=path)


def refusal_of(fn):
    """Run something that must refuse, and hand back the refusal's words.

    Arguments:
      fn = a callable taking no arguments.

    Returns:
      the refusal's message, or None when it did not refuse.
    """
    try:
        fn()
    except ValueError as exc:
        return str(exc)
    return None


def says_how_to_fix(message):
    """Judge whether a refusal tells the reader what to do about it.

    A message that says a file is incompatible and stops is not a refusal, it
    is a shrug. Every refusal in this record names the way out.

    Arguments:
      message = the refusal's message, or None.

    Returns:
      True when the message carries the migration instruction.
    """
    if message is None:
        return False
    return "Re-generate the dataset" in message


def says_what_to_do(message, remedy):
    """Judge whether a comparison law's refusal names the way out.

    The record's own refusals all end in the same instruction, and the helper
    above looks for it: re-generate the dataset, because the file is what is
    wrong. A comparison law cannot say that. The file is fine; the way it is
    being served is not, and the way out differs with the law. Serve the pair
    from one dump. Sample inside the region. Resolve the coordinate in the model
    being sampled. So the caller names the remedy it expects to read, and this
    asks only that the refusal carries it.

    Arguments:
      message = the refusal's message, or None.
      remedy  = the words the refusal must carry to be an instruction and not a
                shrug.

    Returns:
      True when the message names that way out.
    """
    if message is None:
        return False
    return remedy in message


def check_round_trip(work):
    """Both blocks survive the write and the read unchanged.

    Arguments:
      work = a scratch directory to write into.

    Returns:
      None.
    """
    text = sample_sidecar()
    path = os.path.join(work, "round-trip.h5")
    write_artifact(path=path, text=text)
    blocks = read_artifact(path)

    facts = blocks[fixed_facts.FIXED_FACTS_GROUP]
    domain = blocks[fixed_facts.INPUT_DOMAIN_GROUP]

    report("the sampled names survive the round trip, in order",
           domain["names"] == NAMES,
           repr(domain["names"]))
    # a boolean must come back a boolean. HDF5 has no Python types, and in
    # Python True == 1, so an integer that slipped in where a boolean belongs
    # would compare equal to True and never be noticed.
    report("a fixed fact keeps its type, not just its value",
           facts["flat_only"] is True,
           "flat_only is " + repr(facts["flat_only"]))
    report("the cosmology held fixed survives the round trip",
           facts["cosmology_fixed"]["mnu"] == 0.06
           and facts["cosmology_fixed"]["TCMB"] == 2.7255,
           repr(facts["cosmology_fixed"]))
    # the sampled coordinate is NOT among the pinned ones. The record cannot
    # answer "what was w?" two different ways.
    report("a sampled coordinate is absent from the fixed cosmology",
           "w" not in facts["cosmology_fixed"],
           "cosmology_fixed holds " + repr(sorted(facts["cosmology_fixed"])))
    low, high = fixed_facts.domain_bounds(blocks, "w")
    report("a support reads back as the interval it was drawn from",
           low < -1.29 and high > -0.71,
           "w in [" + repr(low) + ", " + repr(high) + "]")
    # the shortest decimal that reads back as the same float32. A coarser
    # format would collapse two distinct bounds into one string.
    report("two bounds that differ in the last float32 digit stay distinct",
           fixed_facts.format_value(70.00001)
           != fixed_facts.format_value(70.00002),
           fixed_facts.format_value(70.00001) + " vs "
           + fixed_facts.format_value(70.00002))


def check_rewritten_record(work):
    """A record rewritten after the file was written is caught and refused.

    The file carries the producer's own text AND the blocks parsed from it. The
    reader checks them against each other in both directions. This is what makes
    "copied verbatim, never re-derived" a statement that can be checked rather
    than a promise that must be trusted.

    Arguments:
      work = a scratch directory to write into.

    Returns:
      None.
    """
    import h5py

    path = os.path.join(work, "rewritten.h5")
    write_artifact(path=path, text=sample_sidecar())
    # edit ONE fact in the stored block, leaving the producer's text alone: the
    # forgery a re-derivation would produce if training became a second author.
    with h5py.File(path, "r+") as f:
        group = f[fixed_facts.FIXED_FACTS_GROUP][ "cosmology_fixed"]
        group.attrs["mnu"] = 0.12

    message = refusal_of(lambda: read_artifact(path))
    report("a fact edited after the write is refused, not believed",
           message is not None and "does not match the producer text" in message,
           (message or "accepted").splitlines()[0][:72])
    report("the refusal shows the file's record beside the producer's",
           message is not None and "the file's record" in message
           and "the producer said" in message,
           "both sides named")

    # the other direction: swap the producer's text under blocks that no longer
    # match it. One-directional checking would miss this.
    other = os.path.join(work, "swapped.h5")
    write_artifact(path=other, text=sample_sidecar())
    with h5py.File(other, "r+") as f:
        del f[fixed_facts.SIDECAR_DATASET]
        dt = h5py.string_dtype(encoding="utf-8")
        f.create_dataset(fixed_facts.SIDECAR_DATASET,
                         data=sample_sidecar(dataset_id="sha256:" + "b" * 64),
                         dtype=dt)
    swapped = refusal_of(lambda: read_artifact(other))
    report("a producer text swapped under its blocks is refused",
           swapped is not None and "does not match the producer text" in swapped,
           (swapped or "accepted").splitlines()[0][:72])


def check_missing_record(work):
    """A file with no record at all is refused, and told how to get one.

    Arguments:
      work = a scratch directory to write into.

    Returns:
      None.
    """
    import h5py

    for group in (fixed_facts.FIXED_FACTS_GROUP,
                  fixed_facts.INPUT_DOMAIN_GROUP,
                  fixed_facts.SIDECAR_DATASET):
        path = os.path.join(work, "no-" + group + ".h5")
        write_artifact(path=path, text=sample_sidecar())
        with h5py.File(path, "r+") as f:
            del f[group]
        message = refusal_of(lambda: read_artifact(path))
        report("a file missing its " + group + " is refused",
               message is not None,
               (message or "accepted").splitlines()[0][:60])
        report("that refusal says how to fix it",
               says_how_to_fix(message),
               "names the re-save path")


def check_legacy_version(work):
    """A record in a grammar this code does not know is refused.

    Both the schema as a whole and each block carry a version. A file written
    before a key existed and a file whose writer forgot that key are different
    files, and a reader that cannot tell them apart will eventually read one as
    the other. So an unknown version is refused rather than guessed at.

    Arguments:
      work = a scratch directory to write into.

    Returns:
      None.
    """
    blocks = fixed_facts.parse_sidecar(text=sample_sidecar(), where="fixture")

    # the two legacy schema versions. Neither carried a record at all, so
    # neither can say which cosmology it was trained under.
    for old in (1, 2):
        message = refusal_of(
            lambda v=old: fixed_facts.validate(blocks=blocks,
                                               where="a version " + str(v)
                                                     + " file",
                                               schema_version=v))
        report("a schema version " + str(old) + " file is refused",
               message is not None,
               (message or "accepted").splitlines()[0][:60])
        report("the version " + str(old) + " refusal says how to migrate",
               says_how_to_fix(message),
               "names the re-save path")

    # a block written in a grammar from the future is refused for the same
    # reason, in the same words.
    future = fixed_facts.parse_sidecar(text=sample_sidecar(), where="fixture")
    future[fixed_facts.FIXED_FACTS_GROUP]["block_version"] = 99
    message = refusal_of(
        lambda: fixed_facts.validate(blocks=future, where="a future file"))
    report("a block grammar this code does not know is refused",
           message is not None and "does not know" in message,
           (message or "accepted").splitlines()[0][:60])

    # the current version is accepted. A check that only ever refuses proves
    # nothing about the file it is supposed to let through.
    accepted = refusal_of(
        lambda: fixed_facts.validate(blocks=blocks, where="the current file"))
    report("the current schema version is accepted",
           accepted is None,
           "version " + str(fixed_facts.SCHEMA_VERSION) + " reads")


def check_sampled_and_fixed():
    """A coordinate cannot be both sampled and held fixed.

    If it were, the two halves of the record would disagree about the same
    number: one would pin it, the other would let it range. The file would then
    answer "what was w?" differently depending on which half was read.

    Returns:
      None.
    """
    message = refusal_of(
        lambda: fixed_facts.build_sidecar(
            dataset_id="sha256:" + "c" * 64,
            generator="dataset_generator_mps",
            family="grid2d",
            # w is sampled below, and pinned here. That is the contradiction.
            cosmology_fixed={"mnu": 0.06, "w": -1.0},
            neutrino_convention="degenerate",
            flat_only=True,
            dark_energy_law="constant-w",
            dark_energy_inputs=["w"],
            cl_units=fixed_facts.NOT_APPLICABLE,
            base_identity=fixed_facts.NOT_APPLICABLE,
            names=NAMES,
            requested=REQUESTED,
            resolved=RESOLVED))
    report("a coordinate both sampled and held fixed is refused at publication",
           message is not None and "both sampled and held fixed" in message,
           (message or "accepted").splitlines()[0][:66])
    report("the refusal names the coordinate and both of its values",
           message is not None and "'w'" in message and "-1.0" in message,
           "names w, its pinned value, and its sampled interval")


def check_parameter_order():
    """The whitening geometry and the record must agree on the parameter order.

    The emulator's input geometry carries its own copy of the sampled names,
    because that is the order its whitening matrices were built in. If it ever
    disagrees with the record, every incoming value is paired with the wrong
    parameter's column: the predictions are then confidently wrong, and nothing
    about the numbers looks unusual. Nothing compared the two lists before.

    Returns:
      None.
    """
    blocks = fixed_facts.parse_sidecar(text=sample_sidecar(), where="fixture")

    same = refusal_of(
        lambda: fixed_facts.check_names_match(geometry_names=NAMES,
                                              blocks=blocks,
                                              where="a faithful emulator"))
    report("a geometry whose order matches the record is accepted",
           same is None,
           "the orders agree")

    # a PERMUTATION: the same names, the same count, a different order. A check
    # that counted the names, or compared them as a set, would let this through,
    # and it is the case that silently corrupts every prediction.
    permuted = [NAMES[1], NAMES[0]] + NAMES[2:]
    message = refusal_of(
        lambda: fixed_facts.check_names_match(geometry_names=permuted,
                                              blocks=blocks,
                                              where="a permuted emulator"))
    report("a geometry whose order is permuted is refused",
           message is not None and "disagree about the sampled parameters"
           in message,
           repr(permuted[:2]) + " against " + repr(NAMES[:2]))
    report("the refusal prints both orders, so the swap is visible",
           message is not None and repr(permuted) in message
           and repr(NAMES) in message,
           "both orders named")


def check_dataset_identity(work):
    """The dataset's identity is the digest of the chain that was published.

    Two independent generator runs can agree on every fixed fact and every
    bound and still be different datasets: same cosmology, same priors, a
    different seed. Comparing the facts cannot tell them apart. The chain's own
    bytes can, because they are the drawn sample.

    Arguments:
      work = a scratch directory to write into.

    Returns:
      None.
    """
    first = os.path.join(work, "params.1.txt")
    with open(first, "w") as f:
        f.write("# weights lnp omegam H0 ns logA w chi2*\n")
        f.write("1.0 1.0 3.0e-01 7.0e+01 9.6e-01 3.0e+00 -1.0e+00 0.0\n")

    # the same facts, the same bounds, a different draw. This is the pair the
    # identity exists to tell apart.
    second = os.path.join(work, "other.1.txt")
    with open(second, "w") as f:
        f.write("# weights lnp omegam H0 ns logA w chi2*\n")
        f.write("1.0 1.0 3.1e-01 7.0e+01 9.6e-01 3.0e+00 -1.0e+00 0.0\n")

    one = fixed_facts.chain_digest(first)
    again = fixed_facts.chain_digest(first)
    two = fixed_facts.chain_digest(second)

    report("the identity recomputes to the same digest from the same bytes",
           one == again,
           one[:23] + "...")
    report("two different draws carry different identities",
           one != two,
           "the digests differ")
    report("the identity is a digest, and says so",
           one.startswith("sha256:") and len(one) == len("sha256:") + 64,
           "sha256, 64 hex digits")

    # and it survives the copy into the artifact, which is the whole point: the
    # emulator carries the identity of the dataset it was trained on.
    path = os.path.join(work, "identity.h5")
    write_artifact(path=path, text=sample_sidecar(dataset_id=one))
    blocks = read_artifact(path)
    stored = blocks[fixed_facts.FIXED_FACTS_GROUP]["dataset_id"]
    report("the emulator carries its dataset's identity, unchanged",
           stored == one,
           "recomputed from the chain and matched")


def check_mutation_arms(work):
    """Break the code on purpose, and prove the legs above go red.

    A check that cannot fail proves nothing. Each arm here reaches into the
    record's own laws, breaks one, confirms the guarding leg reds, and puts it
    back. If an arm ever stops reddening, the leg it guards has gone hollow.

    Arguments:
      work = a scratch directory to write into.

    Returns:
      None.
    """
    import h5py

    # ARM ONE: accept the old schema again. This is the mutation that undoes the
    # version bump, and the legacy-version leg is what stands against it.
    known = fixed_facts.KNOWN_VERSIONS
    fixed_facts.KNOWN_VERSIONS = known + ((2, 1, 1),)
    try:
        blocks = fixed_facts.parse_sidecar(text=sample_sidecar(),
                                           where="fixture")
        leaked = refusal_of(
            lambda: fixed_facts.validate(blocks=blocks,
                                         where="a version 2 file",
                                         schema_version=2))
    finally:
        fixed_facts.KNOWN_VERSIONS = known
    report("mutation: re-accepting the old schema version reds the version leg",
           leaked is None,
           "a version 2 file was accepted while the law was broken")

    # prove the law is back. A mutation arm that leaves the code broken has
    # turned a check into a liability.
    restored = refusal_of(
        lambda: fixed_facts.validate(
            blocks=fixed_facts.parse_sidecar(text=sample_sidecar(),
                                             where="fixture"),
            where="a version 2 file",
            schema_version=2))
    report("the version law is restored after the mutation",
           restored is not None,
           "a version 2 file refuses again")

    # ARM TWO: re-derive the blocks instead of copying them. This is the failure
    # the two-way check exists to catch: training becoming a second author of a
    # scientific fact. Here the file's blocks say one thing and the producer's
    # own text says another, exactly as a re-derivation that drifted would.
    path = os.path.join(work, "re-derived.h5")
    text = sample_sidecar()
    with h5py.File(path, "w") as f:
        f.attrs["schema_version"] = fixed_facts.SCHEMA_VERSION
        fixed_facts.write_h5(f=f, sidecar_text=text)
        # the drift: one bound, re-derived a hair wider than the producer wrote.
        f[fixed_facts.INPUT_DOMAIN_GROUP]["resolved"]["H0"][0] = "55.0"
    caught = refusal_of(lambda: read_artifact(path))
    report("mutation: a re-derived bound that drifts from the producer is caught",
           caught is not None and "does not match the producer text" in caught,
           (caught or "accepted, which is the defect").splitlines()[0][:60])

    # the control: the same file, written faithfully, still reads. An arm that
    # reds everything is not evidence either.
    clean = os.path.join(work, "faithful.h5")
    write_artifact(path=clean, text=text)
    ok = refusal_of(lambda: read_artifact(clean))
    report("the faithful copy of the same record still reads",
           ok is None,
           "the arm reds the drift, not the file")


def check_vertical_law():
    """Does the artifact belong to the cosmology being sampled?

    The artifact was generated with some coordinates held fixed: a neutrino
    mass, a curvature, a photon temperature. Those are not inputs the emulator
    takes. They are properties of the universe it learned. A chain that holds
    any of them at another value is sampling another universe, and the emulator
    will answer anyway: confidently, wrongly, and with numbers that look
    entirely ordinary.

    The law compares the coordinates the ARTIFACT pinned against the resolved
    model, and never looks at the emulator's input axes, which are the domain
    law's business. Comparing the input axes and calling it a cosmology check is
    the confusion this law exists to end.

    Returns:
      None.
    """
    blocks = blocks_of(sample_sidecar())
    held = blocks[fixed_facts.FIXED_FACTS_GROUP]["cosmology_fixed"]

    agreed = refusal_of(
        lambda: fixed_facts.check_vertical(blocks=blocks,
                                           resolved_model=SAMPLED_MODEL,
                                           where="a matching emulator"))
    report("an artifact whose pinned cosmology matches the model is accepted",
           agreed is None,
           "mnu, wa, omk, TCMB and nnu all agree")
    # the model carries w too, and the record samples w rather than pinning it.
    # A law that compared the input axes would have found w here and compared it.
    report("a coordinate the artifact sampled is not compared as a fixed fact",
           agreed is None and "w" not in held,
           "the model's w = -1.0 was never consulted")

    # the same model with the neutrino mass moved. This is a different universe,
    # and the emulator was never shown it.
    moved = dict(SAMPLED_MODEL)
    moved["mnu"] = 0.12
    message = refusal_of(
        lambda: fixed_facts.check_vertical(blocks=blocks,
                                           resolved_model=moved,
                                           where="a mismatched emulator"))
    report("an artifact born under another cosmology is refused",
           message is not None and "mnu" in message,
           (message or "accepted").splitlines()[0][:66])
    report("the refusal names the artifact's value and the sampled value",
           message is not None and "0.06" in message and "0.12" in message,
           "the record's 0.06 against the chain's 0.12")
    remedy = "Serve an emulator generated under this cosmology"
    report("the refusal says what to do about it",
           says_what_to_do(message=message, remedy=remedy),
           "names the remediation")

    # a model that never mentions the neutrino mass at all. The artifact pins it,
    # so the question "do these two agree about mnu?" has no answer, and an
    # unanswerable question is refused rather than assumed away.
    silent = dict(SAMPLED_MODEL)
    del silent["mnu"]
    message = refusal_of(
        lambda: fixed_facts.check_vertical(blocks=blocks,
                                           resolved_model=silent,
                                           where="an emulator pinning mnu"))
    report("a model silent about a coordinate the artifact pins is refused",
           message is not None and "does not say what mnu is" in message,
           (message or "accepted").splitlines()[0][:66])

    # a test double pins every coordinate at "n/a", so it disagrees with a real
    # model about all of them, and this law is where it is caught.
    double = blocks_of(double_sidecar(label="a gate's double"))
    message = refusal_of(
        lambda: fixed_facts.check_vertical(blocks=double,
                                           resolved_model=SAMPLED_MODEL,
                                           where="a test double"))
    report("a test double is refused against a real cosmology",
           message is not None and "'n/a'" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])


def check_horizontal_law():
    """Do these two artifacts belong to each other?

    Two emulators are served together all the time: a Hubble rate beside an
    angular diameter distance, a linear power spectrum beside its nonlinear
    boost. Each pair is combined into ONE prediction, so each pair must come
    from one dataset and one cosmology. Nothing checked that. The consumers
    compared parameter-axis names, which agree between two runs that share a
    prior and differ in every number that matters.

    Returns:
      None.
    """
    first_dump = "sha256:" + "a" * 64
    fresh_seed = "sha256:" + "b" * 64
    one_dump   = "sha256:" + "d" * 64

    one = blocks_of(sample_sidecar(dataset_id=first_dump))
    two = blocks_of(sample_sidecar(dataset_id=first_dump))
    same = refusal_of(
        lambda: fixed_facts.check_horizontal(blocks_a=one,
                                             blocks_b=two,
                                             where_a="the first half",
                                             where_b="the second half"))
    report("two halves of one dump may be served together",
           same is None,
           "one identity, one cosmology, one coordinate list")

    # the case comparing the facts cannot catch: the same YAML run again with a
    # fresh seed. Every fact agrees, every bound agrees, and the two are still
    # different datasets, because they drew different points.
    rerun = blocks_of(sample_sidecar(dataset_id=fresh_seed))
    message = refusal_of(
        lambda: fixed_facts.check_horizontal(blocks_a=one,
                                             blocks_b=rerun,
                                             where_a="the first half",
                                             where_b="a re-run of the same YAML"))
    report("a re-run with a new seed is refused, though every fact agrees",
           message is not None and "different datasets" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])
    report("the refusal names both dataset identities",
           message is not None and first_dump in message
           and fresh_seed in message,
           "both digests printed")

    # two records that pin the same coordinate at two values. They describe two
    # universes, and a prediction built from both halves is built from neither.
    left = blocks_of(pinned_w_sidecar(dataset_id=one_dump, w_value=-1.0))
    right = blocks_of(pinned_w_sidecar(dataset_id=one_dump, w_value=-0.9))
    message = refusal_of(
        lambda: fixed_facts.check_horizontal(blocks_a=left,
                                             blocks_b=right,
                                             where_a="the half pinning w = -1.0",
                                             where_b="the half pinning w = -0.9"))
    # the needle demands the COORDINATE, not just the block it sits in. The
    # block holds six coordinates; a refusal that printed two six-key mappings
    # side by side and left the reader to diff them would satisfy "it named the
    # values" and still fail the person reading it at 2am.
    report("two records that disagree about a fixed fact are refused",
           message is not None and "cosmology_fixed['w']" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])
    report("the refusal names the fact and prints both of its values",
           message is not None and "-1.0" in message and "-0.9" in message,
           "the pinned cosmologies are printed side by side")

    # a half that never sampled w. The coordinates a pair may be asked about are
    # never the union of the two halves: the half that never saw w would answer
    # as though it were pinned, and the two halves would be evaluated at
    # different points inside one prediction.
    half = blocks_of(half_without_w_sidecar(dataset_id=first_dump))
    message = refusal_of(
        lambda: fixed_facts.check_horizontal(blocks_a=one,
                                             blocks_b=half,
                                             where_a="the half that sampled w",
                                             where_b="the half that did not"))
    report("two records sampled over different coordinates are refused",
           message is not None
           and "not sampled over the same coordinates" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])
    report("the refusal prints both coordinate lists",
           message is not None and repr(NAMES) in message
           and repr(NAMES_WITHOUT_W) in message,
           "both orders named")

    # the schema semantics the gates' own served pairs rely on: a double's
    # identity is the digest of its label, so a pair built to match matches.
    pair_one = blocks_of(double_sidecar(label="one served pair"))
    pair_two = blocks_of(double_sidecar(label="one served pair"))
    same = refusal_of(
        lambda: fixed_facts.check_horizontal(blocks_a=pair_one,
                                             blocks_b=pair_two,
                                             where_a="one half of a double pair",
                                             where_b="the other half"))
    report("two doubles built under one label are one dataset",
           same is None,
           "the label's digest is the identity")

    other = blocks_of(double_sidecar(label="a different double"))
    message = refusal_of(
        lambda: fixed_facts.check_horizontal(blocks_a=pair_one,
                                             blocks_b=other,
                                             where_a="a double",
                                             where_b="an unrelated double"))
    report("two doubles built under different labels are refused on identity",
           message is not None and "different datasets" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])


def check_domain_law():
    """May this artifact be asked about this point?

    An emulator interpolates inside the region it was trained over. Outside it,
    it extrapolates: it returns a number of the right shape, with the right
    sign, and no warning. Nothing in a saved emulator used to record the region
    at all, so nothing could refuse.

    The constraint is read FIRST, because it says whether there is an interval
    to compare against at all. That ordering is load-bearing, and this leg
    proves it: a record that declares no support stores its bounds as the string
    "n/a", and float("n/a") raises. The raise is a ValueError, and so is every
    refusal in this module, so a law that reached the bounds would crash in a
    way that reads exactly like a refusal. The leg therefore reads the words of
    the message, never merely the fact that one was raised.

    Returns:
      None.
    """
    blocks = blocks_of(sample_sidecar())

    inside = refusal_of(
        lambda: fixed_facts.check_domain(blocks=blocks,
                                         point=INTERIOR,
                                         where="the artifact"))
    report("a point inside every interval is accepted, extra coordinates and all",
           inside is None,
           "omegab is not a sampled coordinate and is ignored")

    # the endpoints belong to the region. The support is the closed interval the
    # sampler drew from, and a chain that walks to its edge is not extrapolating.
    at_low = {}
    at_high = {}
    for name in NAMES:
        low, high = fixed_facts.domain_bounds(blocks=blocks, name=name)
        at_low[name] = low
        at_high[name] = high
    low_edge = refusal_of(
        lambda: fixed_facts.check_domain(blocks=blocks,
                                         point=at_low,
                                         where="the artifact"))
    high_edge = refusal_of(
        lambda: fixed_facts.check_domain(blocks=blocks,
                                         point=at_high,
                                         where="the artifact"))
    report("both endpoints of every interval are accepted",
           low_edge is None and high_edge is None,
           "the declared support is closed at both ends")

    # one coordinate outside its interval, the rest well inside. The emulator
    # would answer, and the answer would be wrong.
    outside = dict(INTERIOR)
    outside["omegam"] = 0.6
    message = refusal_of(
        lambda: fixed_facts.check_domain(blocks=blocks,
                                         point=outside,
                                         where="the artifact"))
    report("a point outside the region on one coordinate is refused",
           message is not None and "outside it" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])
    report("the refusal names the interval and the value asked about",
           message is not None and "0.104" in message and "0.496" in message
           and "0.6" in message,
           "omegam in [0.104, 0.496], asked about 0.6")
    remedy = "Sample inside it"
    report("the refusal says what to do about it",
           says_what_to_do(message=message, remedy=remedy),
           "names the remediation")

    # a point that never says what one sampled coordinate is. The emulator has a
    # column for it either way, so the missing coordinate cannot be left to a
    # default: a default is a value nobody chose.
    partial = dict(INTERIOR)
    del partial["logA"]
    message = refusal_of(
        lambda: fixed_facts.check_domain(blocks=blocks,
                                         point=partial,
                                         where="the artifact"))
    report("a point that omits a sampled coordinate is refused",
           message is not None and "does not say what logA is" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])

    # the test double: no support at all, so no point may be asked of it.
    double = blocks_of(double_sidecar(label="a gate's double"))
    message = refusal_of(
        lambda: fixed_facts.check_domain(blocks=double,
                                         point=INTERIOR,
                                         where="a test double"))
    report("a record with no declared support refuses every point",
           message is not None and "declares no support" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])
    report("the refusal names the generator that built the double",
           message is not None and "'synthetic'" in message,
           "the double is named as the thing that must not be served")

    # the trap, tested deliberately. Read the double's bounds as numbers and the
    # code does not refuse, it crashes; and the crash is a ValueError, the same
    # class every refusal here is raised as.
    crash = refusal_of(
        lambda: fixed_facts.domain_bounds(blocks=double, name="omegam"))
    report("reading an undeclared record's bounds as numbers really does crash",
           crash is not None and "could not convert string to float" in crash,
           (crash or "returned a number").splitlines()[0][:60])
    report("the domain law refuses before it ever reaches those bounds",
           message is not None
           and "could not convert string to float" not in message,
           "the designed refusal fired, not the float conversion")

    # a support shaped in a way this code does not know. It is refused rather
    # than guessed at, for the same reason an unknown grammar is.
    unknown = blocks_of(sample_sidecar())
    unknown[fixed_facts.INPUT_DOMAIN_GROUP]["constraint"] = "simplex"
    message = refusal_of(
        lambda: fixed_facts.check_domain(blocks=unknown,
                                         point=INTERIOR,
                                         where="a record from the future"))
    report("a support whose shape this code does not know is refused",
           message is not None and "does not know how to compare" in message,
           (message or "accepted, which is the defect").splitlines()[0][:66])
    report("that refusal says how to fix it",
           says_how_to_fix(message),
           "names the re-save path")


def check_served_support():
    """Where may a PAIR be asked? Only where both halves were trained.

    A point inside one half's region and outside the other's is a point where
    one half is extrapolating, and the combined prediction inherits that in
    silence. So the region a pair may be served over is the overlap of the two,
    never the union. This is the one law that intersects, which is exactly why
    the support cannot live in the block that is compared by equality.

    This law answers WHERE a pair may be asked, not WHETHER it may be served at
    all: that is the horizontal law, proved above. The two records here declare
    different supports, which is what makes the overlap observable.

    Returns:
      None.
    """
    lower = blocks_of(box_sidecar(dataset_id="sha256:" + "e" * 64,
                                  omegam_support=(0.1, 0.5)))
    upper = blocks_of(box_sidecar(dataset_id="sha256:" + "f" * 64,
                                  omegam_support=(0.3, 0.9)))

    support = fixed_facts.served_support(blocks_a=lower,
                                         blocks_b=upper,
                                         where_a="the lower half",
                                         where_b="the upper half")
    low, high = support["omegam"]
    report("the pair is served over the overlap of the two regions",
           low == 0.3 and high == 0.5,
           "[0.1, 0.5] with [0.3, 0.9] serves [" + repr(low) + ", "
           + repr(high) + "]")

    # a coordinate the two agree about is served over the whole interval: the
    # overlap of an interval with itself is itself, and nothing is narrowed that
    # did not have to be.
    both_low, both_high = fixed_facts.domain_bounds(blocks=lower, name="H0")
    served_low, served_high = support["H0"]
    report("a coordinate the two agree about is served over its whole interval",
           served_low == both_low and served_high == both_high,
           "H0 in [" + repr(served_low) + ", " + repr(served_high) + "]")

    # two regions that never met. The union would hand back the gap between
    # them, where neither half has ever seen a training point.
    disjoint = blocks_of(box_sidecar(dataset_id="sha256:" + "0" * 64,
                                     omegam_support=(0.6, 0.9)))
    message = refusal_of(
        lambda: fixed_facts.served_support(blocks_a=lower,
                                           blocks_b=disjoint,
                                           where_a="the lower half",
                                           where_b="the disjoint half"))
    report("a pair whose regions do not overlap is refused",
           message is not None and "do not overlap in omegam" in message,
           (message or "served, which is the defect").splitlines()[0][:66])
    report("the refusal prints the region each half covers",
           message is not None and "[0.1, 0.5]" in message
           and "[0.6, 0.9]" in message,
           "both regions named")

    # a test double has no region to intersect with anything.
    double = blocks_of(double_sidecar(label="a gate's double"))
    message = refusal_of(
        lambda: fixed_facts.served_support(blocks_a=lower,
                                           blocks_b=double,
                                           where_a="the lower half",
                                           where_b="a test double"))
    report("a test double in the pair is refused, not intersected",
           message is not None and "'undeclared'" in message,
           (message or "served, which is the defect").splitlines()[0][:66])


# ---------------------------------------------------------------------------
# The weakened laws.
#
# Each is the shipped law with exactly one guard removed, and exists only to be
# installed over the real one for the length of one mutation arm below. None of
# them is ever called by anything else. If an arm ever stops reddening the leg
# it targets, the leg it guards has gone hollow and proves nothing.
# ---------------------------------------------------------------------------


def weakened_vertical(blocks, resolved_model, where):
    """The vertical law that compares only what both sides happen to state.

    This is the law as it gets written when "compare the pinned coordinates"
    is read as "compare the coordinates they have in common": a coordinate the
    model never mentions is skipped instead of refused. It is the plausible
    weakening, and it is the dangerous one. The artifact pins mnu because its
    dataset was generated at that neutrino mass; a chain whose model never
    resolves mnu is not agreeing with the artifact, it is silent about it, and
    silence is not agreement. The emulator answers every point of that chain
    anyway, and the answers are about a universe nobody asked for.

    Arguments:
      blocks         = the artifact's two blocks.
      resolved_model = the sampled cosmology, as a plain mapping.
      where          = the artifact's identity, named in any refusal.

    Returns:
      None.

    Raises:
      ValueError only when the two states of a coordinate disagree; never when
      the model is silent about one.
    """
    held = blocks[fixed_facts.FIXED_FACTS_GROUP]["cosmology_fixed"]
    for name in sorted(held):
        if name not in resolved_model:
            # the removed guard. Everything below is the shipped law.
            continue
        artifact_value = held[name]
        sampled_value = resolved_model[name]
        if artifact_value != sampled_value:
            raise ValueError(
                where + " was generated with " + name + " held fixed at "
                + repr(artifact_value) + ", but the cosmology being sampled has "
                + name + " = " + repr(sampled_value) + ". Serve an emulator "
                "generated under this cosmology.")


def weakened_horizontal(blocks_a, blocks_b, where_a, where_b):
    """The horizontal law with the identity comparison taken out.

    This is the law as a reasonable person writes it the first time: compare the
    facts, compare the coordinate lists, and trust that two records agreeing on
    every fact came from one dataset. They did not. A re-run of the same YAML
    with a fresh seed agrees on every fact and every bound and is a different
    dataset, because it drew different points.

    Arguments:
      blocks_a, blocks_b = the two artifacts' blocks.
      where_a, where_b   = the two artifacts' identities, named in any refusal.

    Returns:
      None.

    Raises:
      ValueError when a fact other than the identity, or the coordinate list,
      disagrees.
    """
    facts_a = blocks_a[fixed_facts.FIXED_FACTS_GROUP]
    facts_b = blocks_b[fixed_facts.FIXED_FACTS_GROUP]
    for key in fixed_facts.FIXED_FACTS_KEYS:
        if key == "dataset_id":
            continue
        if facts_a[key] != facts_b[key]:
            raise ValueError(
                where_a + " and " + where_b + " disagree about " + repr(key)
                + ". Regenerate both halves from one generator run.")

    names_a = list(blocks_a[fixed_facts.INPUT_DOMAIN_GROUP]["names"])
    names_b = list(blocks_b[fixed_facts.INPUT_DOMAIN_GROUP]["names"])
    if names_a != names_b:
        raise ValueError(
            where_a + " and " + where_b + " were not sampled over the same "
            "coordinates. Regenerate both halves from one generator run.")


def weakened_domain_no_constraint(blocks, point, where):
    """The domain law with the constraint read taken out.

    It goes straight to the intervals, as a law that assumes every record is a
    box would. On a record that declares no support the bounds are the string
    "n/a", so this law does not refuse a test double: it crashes on it, inside
    float(). The crash is a ValueError, which is what every refusal in this
    module is too, so it arrives looking exactly like one.

    Arguments:
      blocks = the artifact's two blocks.
      point  = the point being asked about, a mapping name -> value.
      where  = the artifact's identity, named in any refusal.

    Returns:
      None.

    Raises:
      ValueError when a coordinate is missing or outside its interval, and
      whatever float() raises on a support that was never declared.
    """
    domain = blocks[fixed_facts.INPUT_DOMAIN_GROUP]
    for name in domain["names"]:
        if name not in point:
            raise ValueError(
                where + " cannot be asked about a point that does not say what "
                + name + " is. Hand in every coordinate the emulator sampled.")
        low, high = fixed_facts.domain_bounds(blocks=blocks, name=name)
        value = float(point[name])
        if value < low or value > high:
            raise ValueError(
                where + " was trained over " + name + " in ["
                + fixed_facts.format_value(low) + ", "
                + fixed_facts.format_value(high) + "] and is being asked about "
                + repr(value) + ", which is outside it. Sample inside it.")


def weakened_domain_no_interval(blocks, point, where):
    """The domain law with the interval comparison taken out.

    It still reads the constraint, and it still insists the point names every
    sampled coordinate. What it no longer does is compare the value against the
    region, so every point is served and the emulator extrapolates in silence.

    Arguments:
      blocks = the artifact's two blocks.
      point  = the point being asked about, a mapping name -> value.
      where  = the artifact's identity, named in any refusal.

    Returns:
      None.

    Raises:
      ValueError when the record declares no box support, or when the point
      omits a sampled coordinate.
    """
    domain = blocks[fixed_facts.INPUT_DOMAIN_GROUP]
    constraint = domain["constraint"]
    if constraint != "box":
        raise ValueError(
            where + " declares its support as " + repr(constraint) + ", not a "
            "box of per-coordinate intervals. An emulator with no declared "
            "support must not be served.")

    for name in domain["names"]:
        if name not in point:
            raise ValueError(
                where + " cannot be asked about a point that does not say what "
                + name + " is. Hand in every coordinate the emulator sampled.")


def weakened_served_union(blocks_a, blocks_b, where_a, where_b):
    """The served-support law with the overlap replaced by the union.

    One call each way: max becomes min, min becomes max. What comes back is the
    smallest box containing both regions instead of the box they share, so a
    pair whose regions never met is served over the gap between them, where
    neither half has ever seen a training point. The law can no longer refuse at
    all, because the union of two intervals always has its low below its high.

    Arguments:
      blocks_a, blocks_b = the two artifacts' blocks.
      where_a, where_b   = the two artifacts' identities, named in any refusal.

    Returns:
      a mapping name -> (low, high), the union of the two supports.

    Raises:
      ValueError when either record declares no box support.
    """
    for blocks, where in ((blocks_a, where_a), (blocks_b, where_b)):
        constraint = blocks[fixed_facts.INPUT_DOMAIN_GROUP]["constraint"]
        if constraint != "box":
            raise ValueError(
                where + " declares its support as " + repr(constraint) + ", not "
                "a box of per-coordinate intervals. An emulator with no declared "
                "support must not be served.")

    support = {}
    for name in blocks_a[fixed_facts.INPUT_DOMAIN_GROUP]["names"]:
        low_a, high_a = fixed_facts.domain_bounds(blocks=blocks_a, name=name)
        low_b, high_b = fixed_facts.domain_bounds(blocks=blocks_b, name=name)
        low  = min(low_a, low_b)
        high = max(high_a, high_b)
        if low > high:
            raise ValueError(
                "these two emulators were trained over regions that do not "
                "overlap in " + name + ".")
        support[name] = (low, high)
    return support


def check_comparison_mutations():
    """Break each comparison law on purpose, and prove its leg goes red.

    A check that cannot fail proves nothing. Each arm installs the weakened law
    over the shipped one, re-runs the case the leg above rests on, confirms that
    case no longer refuses, and puts the real law back. The closing control then
    proves the faithful record still passes every law, because an arm that left
    the code broken would have turned this whole file into a liability.

    Returns:
      None.
    """
    first_dump = "sha256:" + "a" * 64
    fresh_seed = "sha256:" + "b" * 64

    one = blocks_of(sample_sidecar(dataset_id=first_dump))
    rerun = blocks_of(sample_sidecar(dataset_id=fresh_seed))
    blocks = blocks_of(sample_sidecar())
    double = blocks_of(double_sidecar(label="a gate's double"))
    lower = blocks_of(box_sidecar(dataset_id="sha256:" + "e" * 64,
                                  omegam_support=(0.1, 0.5)))
    upper = blocks_of(box_sidecar(dataset_id="sha256:" + "f" * 64,
                                  omegam_support=(0.3, 0.9)))
    disjoint = blocks_of(box_sidecar(dataset_id="sha256:" + "0" * 64,
                                     omegam_support=(0.6, 0.9)))

    outside = dict(INTERIOR)
    outside["omegam"] = 0.6

    # ARM ONE: a horizontal law that never compares the identity. The re-run with
    # a fresh seed agrees on every fact, so nothing else in the law can catch it.
    real_horizontal = fixed_facts.check_horizontal
    fixed_facts.check_horizontal = weakened_horizontal
    try:
        leaked = refusal_of(
            lambda: fixed_facts.check_horizontal(blocks_a=one,
                                                 blocks_b=rerun,
                                                 where_a="the first half",
                                                 where_b="a re-run"))
    finally:
        fixed_facts.check_horizontal = real_horizontal
    report("mutation: a horizontal law blind to the identity reds its leg",
           leaked is None,
           "the re-run was served beside the original")

    caught = refusal_of(
        lambda: fixed_facts.check_horizontal(blocks_a=one,
                                             blocks_b=rerun,
                                             where_a="the first half",
                                             where_b="a re-run"))
    report("the identity comparison is back after the mutation",
           caught is not None and "different datasets" in caught,
           "the re-run refuses again")

    # ARM TWO: a domain law that never reads the constraint. This is the arm the
    # float("n/a") trap lives in, so it is worth being precise about what red
    # means here. The weakened law still raises on the test double, because
    # reading "n/a" as a number raises. It just no longer refuses: it crashes,
    # and the crash is a ValueError, the same class as every refusal. So the leg
    # cannot ask "did it raise?" and must ask "did it say the designed words?".
    real_domain = fixed_facts.check_domain
    fixed_facts.check_domain = weakened_domain_no_constraint
    try:
        leaked = refusal_of(
            lambda: fixed_facts.check_domain(blocks=double,
                                             point=INTERIOR,
                                             where="a test double"))
    finally:
        fixed_facts.check_domain = real_domain
    designed = leaked is not None and "declares no support" in leaked
    report("mutation: a domain law that ignores the constraint reds its leg",
           not designed,
           "the test double no longer refuses by design")
    report("the weakened law crashes inside float() instead of refusing",
           leaked is not None and "could not convert string to float" in leaked,
           (leaked or "accepted").splitlines()[0][:60])
    # the trap itself, stated as a verdict: a leg written to ask only whether
    # something was raised would have stayed green through this whole mutation.
    report("a leg that asked only whether it raised would have missed this",
           leaked is not None,
           "the crash is a ValueError, and so reads exactly like a refusal")

    restored = refusal_of(
        lambda: fixed_facts.check_domain(blocks=double,
                                         point=INTERIOR,
                                         where="a test double"))
    report("the constraint is read first again after the mutation",
           restored is not None and "declares no support" in restored,
           "the designed refusal is back")

    # ARM THREE: a domain law that never compares the point against the interval.
    fixed_facts.check_domain = weakened_domain_no_interval
    try:
        leaked = refusal_of(
            lambda: fixed_facts.check_domain(blocks=blocks,
                                             point=outside,
                                             where="the artifact"))
    finally:
        fixed_facts.check_domain = real_domain
    report("mutation: a domain law that skips the interval reds its leg",
           leaked is None,
           "omegam = 0.6 was served by a record trained to 0.496")

    caught = refusal_of(
        lambda: fixed_facts.check_domain(blocks=blocks,
                                         point=outside,
                                         where="the artifact"))
    report("the interval comparison is back after the mutation",
           caught is not None and "outside it" in caught,
           "the outside point refuses again")

    # ARM FOUR: the served support taken as the union rather than the overlap.
    # The union of two regions that never met is the gap between them, and the
    # law that returns it can never refuse anything.
    real_served = fixed_facts.served_support
    fixed_facts.served_support = weakened_served_union
    hull = None
    leaked = None
    try:
        hull = fixed_facts.served_support(blocks_a=lower,
                                          blocks_b=disjoint,
                                          where_a="the lower half",
                                          where_b="the disjoint half")
    except ValueError as exc:
        leaked = str(exc)
    finally:
        fixed_facts.served_support = real_served

    if hull is None:
        served = "the disjoint pair refused"
    else:
        served = "omegam served over " + repr(hull["omegam"])
    report("mutation: taking the union instead of the overlap reds its leg",
           leaked is None,
           served)
    report("the weakened law serves the gap between two regions that never met",
           hull is not None and hull["omegam"] == (0.1, 0.9),
           served)

    caught = refusal_of(
        lambda: fixed_facts.served_support(blocks_a=lower,
                                           blocks_b=disjoint,
                                           where_a="the lower half",
                                           where_b="the disjoint half"))
    report("the overlap is back after the mutation",
           caught is not None and "do not overlap" in caught,
           "the disjoint pair refuses again")

    # ARM FIVE: the vertical law that skips a coordinate the model is silent
    # about. The other three laws each had an arm from the day they landed; this
    # one did not, and its refusal legs were load-bearing all the same. The arm
    # is what makes that checkable rather than believed.
    silent = dict(SAMPLED_MODEL)
    del silent["mnu"]
    real_vertical = fixed_facts.check_vertical
    fixed_facts.check_vertical = weakened_vertical
    try:
        leaked = refusal_of(
            lambda: fixed_facts.check_vertical(blocks=blocks,
                                               resolved_model=silent,
                                               where="an emulator pinning mnu"))
    finally:
        fixed_facts.check_vertical = real_vertical
    report("mutation: a vertical law that skips what the model omits reds its leg",
           leaked is None,
           "a chain silent about mnu was served an emulator pinned at 0.06")

    caught = refusal_of(
        lambda: fixed_facts.check_vertical(blocks=blocks,
                                           resolved_model=silent,
                                           where="an emulator pinning mnu"))
    report("the silent-coordinate refusal is back after the mutation",
           caught is not None and "does not say what mnu is" in caught,
           "silence is refused again, and named")

    # the closing control. Every law is restored, and the faithful record still
    # passes all four: the arms red the mutation, not the record.
    twin = blocks_of(sample_sidecar(dataset_id=first_dump))
    ok_pair = refusal_of(
        lambda: fixed_facts.check_horizontal(blocks_a=one,
                                             blocks_b=twin,
                                             where_a="the first half",
                                             where_b="the second half"))
    ok_model = refusal_of(
        lambda: fixed_facts.check_vertical(blocks=blocks,
                                           resolved_model=SAMPLED_MODEL,
                                           where="the artifact"))
    ok_point = refusal_of(
        lambda: fixed_facts.check_domain(blocks=blocks,
                                         point=INTERIOR,
                                         where="the artifact"))
    ok_region = refusal_of(
        lambda: fixed_facts.served_support(blocks_a=lower,
                                           blocks_b=upper,
                                           where_a="the lower half",
                                           where_b="the upper half"))
    report("with every law restored, the faithful record still passes all four",
           ok_pair is None and ok_model is None and ok_point is None
           and ok_region is None,
           "the arms red the mutation, not the record")


# ---------------------------------------------------------------------------
# The resolved model, and the one reader of it.
#
# The producer reads the resolved Cobaya model to WRITE the record; each cobaya
# adapter reads the same model, at chain setup, to CHECK an artifact's record
# against the cosmology now being sampled. Those two readings must agree down to
# which block wins a name that two blocks state, so there is ONE reader and both
# call it.
#
# The doubles below are the smallest thing that reader accepts. They are not
# cobaya: the reader duck-types the model, which is exactly why the module can
# stay free of cobaya (and of torch), and why this leg runs on a bare numpy
# interpreter.
# ---------------------------------------------------------------------------


class FakeParameterization:
    """The params block of a resolved model: the constants it states."""

    def __init__(self, constants):
        self._constants = constants

    def constant_params(self):
        """The parameters this run wrote as a plain number."""
        return self._constants


class FakeComponent:
    """One theory component of a resolved model, carrying its extra_args."""

    def __init__(self, extra_args):
        self.extra_args = extra_args


class FakeModel:
    """A resolved model, exposing the two surfaces the reader reads.

    Arguments:
      components = the theory components, in the order the model lists them.
      constants  = the params block's constants.
    """

    def __init__(self, components, constants):
        self.theory = {}
        for i in range(len(components)):
            self.theory["component" + str(i)] = components[i]
        self.parameterization = FakeParameterization(constants=constants)


class ModelWithoutTheory:
    """A model whose theory collection cannot be walked at all.

    A cobaya that does not expose one of these surfaces must leave the facts it
    would have supplied unresolved, not kill a generator run whose data vectors
    are already computed. The reader wraps every lookup for that reason, and this
    double is what proves the wrapping is real: reading .theory raises.
    """

    def __init__(self, constants):
        self.parameterization = FakeParameterization(constants=constants)

    @property
    def theory(self):
        raise RuntimeError("this cobaya does not expose a theory collection")


def check_resolved_constants():
    """One reader of the resolved model, and the precedence it reads under.

    The record's facts come from two places in the resolved model, and they can
    both state one name. Which one wins is a scientific decision, not a detail:
    the params block is the model's own parameterization of the cosmology, so it
    wins over a setting handed to the Boltzmann code. If the producer and the
    adapters ever disagreed about that, one of them would write a fact the other
    would refuse, and the emulator would be unservable in the chain it was
    generated for.

    Returns:
      None.
    """
    camb = FakeComponent(extra_args={"nnu": 3.044, "mnu": 0.1, "halofit": "mead"})
    second = FakeComponent(extra_args={"mnu": 0.2, "TCMB": 2.7255})

    resolved = fixed_facts.resolved_constants(
        model=FakeModel(components=[camb, second],
                        constants={"mnu": 0.06, "w": -1.0}))

    report("a theory component's extra_args reach the record",
           resolved.get("halofit") == "mead",
           "halofit = " + repr(resolved.get("halofit")))
    report("the params block wins a name both blocks state",
           resolved.get("mnu") == 0.06,
           "the model pins mnu at 0.06; the theory block asked for 0.1")
    report("the first component wins a name two components state",
           resolved.get("TCMB") == 2.7255,
           "the second component's mnu = 0.2 never displaced the first's 0.1 "
           "before the params block overwrote both")
    report("every constant the params block states is read",
           resolved.get("w") == -1.0,
           "w = " + repr(resolved.get("w")))

    # the values are reduced to plain facts on the way in, because the record is
    # written as YAML and copied into HDF5, and both store plain values. A
    # boolean is tested before a number: in Python True equals 1, and a flag
    # stored as the float 1.0 reads back as a number that was never a flag.
    flags = fixed_facts.resolved_constants(
        model=FakeModel(components=[FakeComponent(extra_args={"lensing": True})],
                        constants={"nnu": 3, "share_delta_neff": False}))
    report("a flag stays a flag and a number becomes a number",
           flags["lensing"] is True and flags["share_delta_neff"] is False
           and flags["nnu"] == 3.0 and isinstance(flags["nnu"], float),
           "lensing = True, nnu = 3.0")

    # a cobaya that cannot be walked leaves the facts it would have supplied
    # ABSENT, rather than crashing a run whose data vectors are already computed.
    # Absent is a fact the record publishes as "n/a"; a crash is a lost run.
    degraded = fixed_facts.resolved_constants(
        model=ModelWithoutTheory(constants={"mnu": 0.06}))
    report("a model that cannot be walked degrades to absence, not to a crash",
           degraded == {"mnu": 0.06},
           "the theory block was unreadable; the params block still resolved")

    empty = fixed_facts.resolved_constants(model=ModelWithoutTheory(constants={}))
    report("a model that resolves nothing resolves nothing, quietly",
           empty == {},
           "no facts, no crash — the record publishes 'n/a' for each of them")


def main():
    """Run every leg, and account for every leg the board expects.

    Returns:
      0 when every leg passed, 1 otherwise.
    """
    work = tempfile.mkdtemp(prefix="fixed-facts-schema-")
    emitted = set()
    blocker = None
    try:
        print("\n-- the record survives the round trip --")
        n0 = len(FAILURES)
        check_round_trip(work)
        aid = "fixed-facts-schema.record-round-trip"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- a record rewritten after the write is caught --")
        n0 = len(FAILURES)
        check_rewritten_record(work)
        aid = "fixed-facts-schema.rewritten-record-refused"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- a file with no record is refused --")
        n0 = len(FAILURES)
        check_missing_record(work)
        aid = "fixed-facts-schema.missing-record-refused"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- an unknown grammar is refused --")
        n0 = len(FAILURES)
        check_legacy_version(work)
        aid = "fixed-facts-schema.legacy-version-refused"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- a coordinate cannot be both sampled and fixed --")
        n0 = len(FAILURES)
        check_sampled_and_fixed()
        aid = "fixed-facts-schema.sampled-and-fixed-refused"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- the geometry and the record agree on the order --")
        n0 = len(FAILURES)
        check_parameter_order()
        aid = "fixed-facts-schema.parameter-order-enforced"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- the identity is the published chain's digest --")
        n0 = len(FAILURES)
        check_dataset_identity(work)
        check_mutation_arms(work)
        aid = "fixed-facts-schema.dataset-identity-is-the-chain"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- the artifact belongs to the cosmology being sampled --")
        n0 = len(FAILURES)
        check_vertical_law()
        aid = "fixed-facts-schema.vertical-law-enforced"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- the two artifacts belong to each other --")
        n0 = len(FAILURES)
        check_horizontal_law()
        aid = "fixed-facts-schema.horizontal-law-enforced"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- the artifact is asked only inside the region it learned --")
        n0 = len(FAILURES)
        check_domain_law()
        aid = "fixed-facts-schema.domain-law-enforced"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- a pair is served over the overlap, never the union --")
        n0 = len(FAILURES)
        check_served_support()
        aid = "fixed-facts-schema.served-support-is-the-intersection"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- every comparison law is load-bearing --")
        n0 = len(FAILURES)
        check_comparison_mutations()
        aid = "fixed-facts-schema.comparison-laws-are-load-bearing"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)

        print("\n-- the resolved model is read by one reader --")
        n0 = len(FAILURES)
        check_resolved_constants()
        aid = "fixed-facts-schema.resolved-model-read-once"
        if not emit_leg(aid, n0):
            blocker = aid
        emitted.add(aid)
    finally:
        shutil.rmtree(work, ignore_errors=True)
        # A leg whose group was skipped by an upstream failure, or by a crash
        # before any leg reached its terminal, did not run. Emit it as never
        # having run, naming the blocker, so what the board expects and what the
        # check produced agree, and the log points at the leg to fix first.
        for aid in LEG_AIDS:
            if aid not in emitted:
                emit_unavailable(aid, blocker)

    print("")
    if len(FAILURES) == 0:
        print("fixed-facts-schema: ALL PASS")
        return 0
    print("fixed-facts-schema: " + str(len(FAILURES)) + " FAILURE(S): "
          + ", ".join(FAILURES))
    return 1


if __name__ == "__main__":
    sys.exit(main())
