"""Run D0's protected-ticket harness against real disposable Git commits."""

import importlib.util
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest


SOURCE_ROOT = Path(__file__).resolve().parents[2]
CONTROLLER_FILES = (
    "ai/tools/mailbox_daemon.py",
    "ai/tools/handoff_contract.py",
    "ai/tools/role_contract.py",
    "ai/notes/role-contract.yaml",
)


def git(repository, *arguments):
  """Run one Git command in the disposable controller repository."""
  result = subprocess.run(
      ["git", "-C", str(repository), *arguments], check=True,
      stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
  return result.stdout.strip()


def make_controller_repository(parent):
  """Commit the current controller files without touching the live checkout."""
  repository = Path(parent) / "controller"
  git(parent, "init", "--quiet", str(repository))
  git(repository, "config", "user.name", "D0 shadow test")
  git(repository, "config", "user.email", "shadow@example.invalid")
  for relative in CONTROLLER_FILES:
    destination = repository / relative
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SOURCE_ROOT / relative, destination)
  git(repository, "add", *CONTROLLER_FILES)
  git(repository, "commit", "--quiet", "-m", "trusted D0")
  git(repository, "branch", "-M", "main")
  return repository, git(repository, "rev-parse", "HEAD")


def load_controller(repository):
  """Load D0 from its own committed path before a proposed D1 is written."""
  path = repository / "ai/tools/mailbox_daemon.py"
  name = "trusted_shadow_driver_" + os.urandom(8).hex()
  spec = importlib.util.spec_from_file_location(name, path)
  module = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(module)
  return module


class ProtectedControlPlaneShadowTests(unittest.TestCase):
  """Prove the trusted harness drives D1 instead of trusting its tests."""

  def test_current_controller_passes_real_state_and_landing_scenarios(self):
    """The D0 probe reaches restart, one-parent L, and stale-main checks."""
    with tempfile.TemporaryDirectory(prefix="protected-shadow-pass-") as tmp:
      repository, candidate = make_controller_repository(tmp)
      d0 = load_controller(repository)
      refs_before = git(
          repository, "for-each-ref", "--format=%(refname) %(objectname)",
          d0.CANDIDATE_REF_ROOT, "refs/heads/main")

      passed, log_path = d0.trusted_control_plane_check(
          commit=candidate, label="focused-pass")

      self.assertTrue(passed)
      log = Path(log_path).read_text(encoding="utf-8")
      self.assertIn("D0_SHADOW_SCENARIOS_PASSED", log)
      self.assertEqual(
          git(repository, "for-each-ref",
              "--format=%(refname) %(objectname)",
              d0.CANDIDATE_REF_ROOT, "refs/heads/main"),
          refs_before)
      self.assertFalse(Path(d0.ticket_cycle_state_path()).exists())
      self.assertFalse(Path(d0.candidate_state_path()).exists())

  def test_d0_detects_a_candidate_that_weakens_stale_main_refusal(self):
    """A D1 landing shortcut fails the D0-owned real-path scenario."""
    with tempfile.TemporaryDirectory(prefix="protected-shadow-stale-") as tmp:
      repository, _base = make_controller_repository(tmp)
      d0 = load_controller(repository)
      daemon_path = repository / "ai/tools/mailbox_daemon.py"
      source = daemon_path.read_text(encoding="utf-8")
      boundary = "    if current_main in {parent_commit, landing_commit}:\n"
      self.assertEqual(source.count(boundary), 1)
      daemon_path.write_text(
          source.replace(boundary, "    return None\n" + boundary),
          encoding="utf-8")
      git(repository, "add", "ai/tools/mailbox_daemon.py")
      git(repository, "commit", "--quiet", "-m", "weaken stale guard")
      candidate = git(repository, "rev-parse", "HEAD")

      passed, log_path = d0.trusted_control_plane_check(
          commit=candidate, label="focused-stale-refusal")

      self.assertFalse(passed)
      self.assertIn(
          "changed main reused a stale protected landing",
          Path(log_path).read_text(encoding="utf-8"))

  def test_candidate_test_code_is_not_part_of_the_trusted_harness(self):
    """A candidate test cannot replace the scenarios generated by D0."""
    with tempfile.TemporaryDirectory(prefix="protected-shadow-tests-") as tmp:
      repository, _base = make_controller_repository(tmp)
      d0 = load_controller(repository)
      candidate_test = repository / "ai/tests/test_untrusted_shadow.py"
      candidate_test.parent.mkdir(parents=True, exist_ok=True)
      candidate_test.write_text(
          "raise RuntimeError('candidate test must not be imported')\n",
          encoding="utf-8")
      git(repository, "add", "ai/tests/test_untrusted_shadow.py")
      git(repository, "commit", "--quiet", "-m", "untrusted candidate test")
      candidate = git(repository, "rev-parse", "HEAD")

      passed, log_path = d0.trusted_control_plane_check(
          commit=candidate, label="focused-untrusted-test")

      self.assertTrue(passed)
      log = Path(log_path).read_text(encoding="utf-8")
      self.assertIn("D0_SHADOW_SCENARIOS_PASSED", log)
      self.assertNotIn("candidate test must not be imported", log)


if __name__ == "__main__":
  unittest.main()
